services:
  web:
    build: ./ui
    container_name: scaling_palm_tree_ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
    env_file:
      - ./ui/.env

  server:
    build: ./server
    container_name: scaling_palm_tree_server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./server/.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
