version: '3.9'

services:
  web:
    build: .
    container_name: scaling_palm_tree
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
