# Generated by Django 5.2.5 on 2025-08-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_assistant_url', models.CharField()),
                ('domain', models.CharField()),
                ('entity_id', models.CharField()),
                ('friendly_name', models.CharField()),
            ],
        ),
    ]
