# Generated by Django 5.2.5 on 2025-08-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('home_assistant_url', 'entity_id'), name='unique_entities'),
        ),
    ]
