# Generated by Django 5.2.5 on 2025-08-26 17:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0002_device_unique_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lowercase_group_name')],
            },
        ),
        migrations.CreateModel(
            name='DeviceGroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palm.device')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palm.devicegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device_id', 'group_id'), name='unique_device_group_membership')],
            },
        ),
    ]
