# Generated by Django 5.2.5 on 2025-08-26 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0003_devicegroup_devicegroupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
