# Generated by Django 5.2.5 on 2025-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0004_devicegroup_timestamp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devicegroup',
            name='unique_lowercase_group_name',
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='home_assistant_url',
            field=models.CharField(default='Invalid remove this row'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='devicegroup',
            constraint=models.UniqueConstraint(fields=('name', 'home_assistant_url'), name='unique_lowercase_group_name'),
        ),
    ]
