# Generated by Django 5.2.5 on 2025-08-28 20:59
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0005_remove_devicegroup_unique_lowercase_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devicegroupmembers',
            name='unique_device_group_membership',
        ),
        migrations.RemoveField(
            model_name='devicegroupmembers',
            name='device_id',
        ),
        migrations.AddField(
            model_name='devicegroupmembers',
            name='entity_id',
            field=models.CharField(default='DELETE ROW'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='devicegroupmembers',
            constraint=models.UniqueConstraint(fields=('entity_id', 'group_id'), name='unique_device_group_membership'),
        ),
    ]
