# Generated by Django 5.2.5 on 2025-08-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0006_remove_devicegroupmembers_unique_device_group_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicegroupmembers',
            old_name='group_id',
            new_name='group',
        ),
    ]
