# Generated by Django 5.2.5 on 2025-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0007_rename_group_id_devicegroupmembers_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='devicegroupmembers',
            name='unique_device_group_membership',
        ),
        migrations.AddConstraint(
            model_name='devicegroupmembers',
            constraint=models.UniqueConstraint(fields=('entity_id', 'group'), name='unique_device_group_membership'),
        ),
    ]
