import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./_components/ui/provider";
import { NavHeader } from "./_components/nav_header";
import { inter } from "./fonts";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Provider>
          <NavHeader />
          <Container maxWidth={"80vw"} margin={"0 auto"} width={"100%"}>
            {children}
          </Container>
        </Provider>
      </body>
    </html>
  );
}
